base.url=https://practice.expandtesting.com/notes/app
api.base.url=https://practice.expandtesting.com/notes/api
browser=chrome
loginDataPath=src/test/resources/testdata/testdata.csv
notesDataPath=src/test/resources/testdata/notesdata.csv
jmeter.path=C:\\Users\\debi2\\Downloads\\apache-jmeter-5.6.3\\bin\\jmeter.bat
screenshot_dir=target/screenshots/
